# mapping of html start/end tags to latex tags
start_map = {
'A': '\\href',
'B': '\\textbf',
'BODY': '\\begin{document}',
'CENTER': '\\begin{center}',
'EM': '\\emph',
'FONT': '\\fontsize',
'DIV': '\\section',
'DL': '\\begin{itemize}[label={}]',
'DT': '\\item',
'DD': '\\subitem',
'I': '\\textit',
'H1': '\\section',
'H2': '\\subsection',
'H3': '\\subsubsection',
'H4': '\\paragraph',
'HEAD': '\\usepackage',
'HTML': '\\documentclass',
'LI': '\\item',
'OL': '\\begin{enumerate}',
'P': '\\par',
'SMALL': '\\tiny',
'STRONG': '\\textbf',
'SUB': '\\textsubscript',
'SUP': '\\textsuperscript',
'TABLE': '\\begin{tabular}',
'TITLE': '\\title',
'TD': '&',
'TR': '\\\\',
'TT': '\\texttt',
'U': '\\underline',
'UL': '\\begin{itemize}'
}

# mapping of self closing html tags to latex tags
noclose_map = {
'IMG': r'\figure',
'BR': r'\newline'
}

# mapping of special characters/ greek symbols in html to latex 
text_map = {
	'#': r'\#',
	'{': r'\{', 
	'}': r'\}',
	'$': r'\$', 
	'%': r'\%',
	'&': r'\&',
	'_': r'\_',
	'-': r'\-',
	'^': r'\^{}', 
	'~': r'\~{}',
	'<': r'$<$', 
	'>': r'$>$',
	'&alpha': r'\alpha',
	'&beta': r'\beta',
	'&gamma' : r'\gamma',
	'&delta' : r'\delta',
	'&epsilon' : r'\epsilon',
	'&zeta' : r'\zeta',
	'&eta' : r'\eta',
	'&theta' : r'\theta',
	'&lambda' : r'\lambda',
	'&xi' : r'\xi',
	'&pi' : r'\pi',
	'&rho' : r'\rho',
	'&sigma' : r'\sigma',
	'&tau' : r'\tau',
	'&upsilon' : r'\upsilon',
	'&phi' : r'\phi',
	'&omega' : r'\omega',
	'&Alpha': r'\Alpha',
	'&Beta': r'\Beta',
	'&Gamma' : r'\Gamma',
	'&Delta' : r'\Delta',
	'&Epsilon' : r'\Epsilon',
	'&Zeta' : r'\Zeta',
	'&Eta' : r'\Eta',
	'&Theta' : r'\Theta',
	'&Lambda' : r'\Lambda',
	'&Xi' : r'\Xi',
	'&Pi' : r'\Pi',
	'&Rho' : r'\Rho',
	'&Sigma' : r'\Sigma',
	'&Tau' : r'\Tau',
	'&Upsilon' : r'\Upsilon',
	'&Phi' : r'\Phi',
	'&Omega' : r'\Omega',
	}
	# '\\': r'$\backslash$'
